### ISSUE TITLE
A new config file is made everytime I load the game and it overwrites my config.

### ISSUE THREAD

**Issue by Lcannine** [croissantnova/SanityDescentIntoMadness#24]
Title. I'm not sure if this is a bug or if I need to do something else to fix it.

**Comment by croissantnova** [comment]
Make sure the config syntax is correct is all I can advise. Also try to reproduce the problem with other mods to see if it's tied to this particular mod. I don't know the specifics of Forge handling config files, so if the issue persists you can try getting help on Forge forums.

**Comment by Lcannine** [comment]
I'm trying to modify the blocks to remove the campfire, what would the correct syntax be? Or are you talking about the file name?

**Comment by Lcannine** [comment]
> Make sure the config syntax is correct is all I can advise. Also try to reproduce the problem with other mods to see if it's tied to this particular mod. I don't know the specifics of Forge handling config files, so if the issue persists you can try getting help on Forge forums.

Also, it's tied to this mod in particular.

**Comment by Lcannine** [comment]
Somehow resolved it.
