### ISSUE TITLE
config option for blocks affecting your sanity by being near them or breaking them not working

### ISSUE THREAD

**Issue by veccyboi** [croissantnova/SanityDescentIntoMadness#37]
I am playing the create:arcane engineering modpack on forge 1.18,2-40.2.14 with some extra mods I added myself
mods folder: 
![image](https://github.com/croissantnova/SanityDescentIntoMadness/assets/85643556/d62a0789-c207-4690-bd05-97c3cb87b11c)

bug: I recently added this mod and decided to mess with some of the configs. i wanted to make it so that if you stood next to or broke certain ores (such as lead from thermal series and vanilla redstone) sanity would decrease as if the player was getting poisoned. 
config file currently looks like this: 
[default.txt](https://github.com/croissantnova/SanityDescentIntoMadness/files/13542515/default.txt)
in both the blocks and broken_blocks arrays I have added all lead and redstone-related blocks with the proper syntax, and yet when I load a fresh instance, sanity only decreases next to redstone dust but not any of the other blocks i added.

I am aware of a similar issue (#9 ) but that is for 1.19.2, this is 1.18.2

any help would be appreciated

**Comment by croissantnova** [comment]
There are parts of the config that are unoptimized and not thought out or just straight up broken. Hopefully I'll be able to redo the whole thing and also make it universal across multiple modloaders in the next hopefully big hopefully update I'm hopefully planning.

**Comment by veccyboi** [comment]
oof
other than that though, really nice mod
