### ISSUE TITLE
[Question] Is there anything that can instantly drain ALL your sanity?

### ISSUE THREAD

**Issue by Cheesedoghotdog** [croissantnova/SanityDescentIntoMadness#54]
I was just chilling in my treehouse when I went from full to no sanity in a second. To be fair, I am playing a large, selfmade modpack so I expect some bugs. Just wanna make sure this is an issue and not a feature!

**Comment by croissantnova** [comment]
You should probably take a look at the config. By default lightnings and pet deaths cause the most amount of instant sanity drain, and looking continuously at an enderman can drain a lot of sanity too in a matter of seconds.

**Comment by Cheesedoghotdog** [comment]
I guess it was lightning then. It was during a storm. Cursed Weather2 mod strikes again. Thanks!
